In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('glass.csv')
df.head()

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [4]:
df.isnull().sum()

RI      0
Na      0
Mg      0
Al      0
Si      0
K       0
Ca      0
Ba      0
Fe      0
Type    0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   RI      214 non-null    float64
 1   Na      214 non-null    float64
 2   Mg      214 non-null    float64
 3   Al      214 non-null    float64
 4   Si      214 non-null    float64
 5   K       214 non-null    float64
 6   Ca      214 non-null    float64
 7   Ba      214 non-null    float64
 8   Fe      214 non-null    float64
 9   Type    214 non-null    int64  
dtypes: float64(9), int64(1)
memory usage: 16.8 KB


In [6]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [7]:
from sklearn.model_selection import train_test_split

In [172]:
x_train , x_temp , y_train , y_temp = train_test_split(x,y,test_size = 0.3, random_state = 90)
x_val , x_test , y_val , y_test = train_test_split(x_temp , y_temp , test_size = 0.4, random_state = 30)

In [75]:
from sklearn.tree import DecisionTreeClassifier

In [173]:
decision_tree_model = DecisionTreeClassifier(max_depth = 5, random_state = 0)
decision_tree_model.fit(x_train , y_train)

DecisionTreeClassifier(max_depth=5, random_state=0)

In [174]:
y_pred = decision_tree_model.predict(x_test)

In [78]:
from sklearn.metrics import confusion_matrix , classification_report , f1_score

In [175]:
print('confusion matrix :' , confusion_matrix(y_test , y_pred))
print('classification report :' , classification_report(y_test , y_pred))

confusion matrix : [[8 0 0 0 0]
 [1 6 0 0 2]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 1 0 6]]
classification report :               precision    recall  f1-score   support

           1       0.89      1.00      0.94         8
           2       1.00      0.67      0.80         9
           5       0.50      1.00      0.67         1
           6       1.00      1.00      1.00         1
           7       0.75      0.86      0.80         7

    accuracy                           0.85        26
   macro avg       0.83      0.90      0.84        26
weighted avg       0.88      0.85      0.85        26

